/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test */

#ifndef _Included_com_amlogic_HdmiSwitch_HdmiSwitch
#define _Included_com_amlogic_HdmiSwitch_HdmiSwitch
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_com_amlogic_HdmiSwitch_HdmiSwitch_scaleFrameBufferJni
  (JNIEnv *, jobject ,jint);

#ifdef __cplusplus
}
#endif
#endif
